#!/usr/bin/env bash
#Bash (init) script to-manage_my_process that manages manage_my_process script
case "$1" in
	start)
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		pkill -f ./manage_my_process
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		pkill -f ./manage_my_process
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
	#making sure to handle no parameter
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
esac




